--[[ Generated with https://github.com/TypeScriptToLua/TypeScriptToLua ]]
local ____exports = {}
import("CoreLibs/timer")
import("CoreLibs/object")
import("game/utils")
import("game/tables/table")
import("game/tables/brewing-table")
import("game/tables/client-table")
import("game/tables/ingredients-table")
import("game/stations/station")
import("game/stations/cutting-station")
import("game/stations/burning-station")
import("game/stations/enchantment-station")
import("game/stations/grinding-station")
import("how-to-play-stage")
import("main-menu-stage")
import("story-stage")
import("engine/engine")
import("engine/font")
import("engine/frame")
import("engine/input")
import("engine/sounds")
import("engine/stage")
import("engine/textures")
import("game/game-state")
import("game/ingredients")
import("game/message-board")
import("game/messages")
import("game/potion-names")
import("game/recipe-logic")
import("game/recipes")
import("game/workshop-stage")
import("day-summary-stage");
(function(self)
    Textures:loadTextures()
    local initialStage = MainMenuStage()
    Engine:changeStage(initialStage)
end)(nil)
playdate.update = function()
    playdate.graphics.clear(Engine.secondaryColor)
    playdate.graphics.setColor(Engine.primaryColor)
    local stage = Engine.activeStage
    stage:update()
    stage:render()
    if Engine.shouldCountTicks then
        Engine.ticks = Engine.ticks + 1
    end
    playdate.timer.updateTimers()
end
return ____exports
